apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world-cronjob
  namespace: turn-off-cluster
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-world
            image: busybox
            args:
            - /bin/sh
            - -c
            - echo "hello world"
          restartPolicy: OnFailure