apiVersion: batch/v1
kind: CronJob
metadata:
  name: python-job
  namespace: turn-off-cluster
spec:
  schedule: "45 13 * * *"  # Every 5 minutes
  suspend: true
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            azure.workload.identity/use: "true"  # Required label for workload identity
        spec:
          serviceAccountName: turn-off-cluster-mi
          containers:
          - name: hello-world
            image: python:3.12-slim
            command:
            - /bin/sh
            - -c
            - pip install azure-identity azure-mgmt-containerservice && sleep 600
          restartPolicy: OnFailure