apiVersion: batch/v1
kind: CronJob
metadata:
  name: python-job
  namespace: turn-off-cluster
spec:
  schedule: "0 20 * * * "  # Every 5 minutes
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-world
            image: python:3.12-slim
            command:
            - /bin/sh
            - -c
            - pip install azure-identity azure-mgmt-containerservice && sleep 600
          restartPolicy: OnFailure