apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: crossplane-stable
  namespace: flux-system
spec:
  url: https://charts.crossplane.io/stable
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane-system
  namespace: flux-system
spec:
  targetNamespace: crossplane-system
  interval: 10m  # Add the interval field here
  chart:
    spec:
      chart: crossplane
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
        namespace: flux-system
---
apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aks-d-devops2-uks
spec:
  clientID: ad9bdbcf-02a8-4fb7-b1d5-d11c8c2cffaf
  credentials:
    source: UserAssignedManagedIdentity
  subscriptionID: b133cf1b-9061-473a-a041-99c71f10c773
  tenantID: 9c3053bb-1522-475e-82b2-b426b68a8004