apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  namespace: crossplane-system
spec:
  credentials:
    source: UserAssignedManagedIdentity
  clientID: "bb15cfc3-538c-4873-bc31-392e503dde14"
  subscriptionID: "b133cf1b-9061-473a-a041-99c71f10c773"
  tenantID: "9c3053bb-1522-475e-82b2-b426b68a8004"
---
apiVersion: storage.azure.upbound.io/v1beta1
kind: Account
metadata:
  name: mycrossplanedsa
  namespace: crossplane-system
spec:
  forProvider:
    accountKind: StorageV2
    accountReplicationType: LRS
    accountTier: Standard
    allowNestedItemsToBePublic: false
    isHnsEnabled: true
    location: UK South
    publicNetworkAccessEnabled: false
    resourceGroupName: main_cluster
  providerConfigRef:
    name: default
---
apiVersion: managedidentity.azure.upbound.io/v1beta1
kind: UserAssignedIdentity
metadata:
  name: newmi
spec:
  forProvider:
    location: West Europe
    name: crossplanedmanagedidentity
    resourceGroupName: main_cluster
---
apiVersion: managedidentity.azure.upbound.io/v1beta1
kind: FederatedIdentityCredential
metadata:
  name: newmifederated
spec:
  forProvider:
    audience:
      - "api://AzureADTokenExchange"
    issuer: "https://westeurope.oic.prod-aks.azure.com/9c3053bb-1522-475e-82b2-b426b68a8004/61cd0ea9-54c9-4949-875f-530f3013b097/"
    parentIdRef: newmi
    resourceGroupName: main_cluster
    subject: "system:serviceaccount:default:federated-creds"