# apiVersion: azure.upbound.io/v1beta1
# kind: ProviderConfig
# metadata:
#   name: default
#   namespace: crossplane-system
# spec:
#   credentials:
#     source: UserAssignedManagedIdentity
#   clientID: "efb4cccd-ae27-4143-bcad-a5ff07fea049"
#   subscriptionID: "b133cf1b-9061-473a-a041-99c71f10c773"
#   tenantID: "9c3053bb-1522-475e-82b2-b426b68a8004"
# ---
# apiVersion: storage.azure.upbound.io/v1beta1
# kind: Account
# metadata:
#   name: my-crossplaned-sa
#   namespace: crossplane-system
# spec:
#   forProvider:
#     accountKind: StorageV2
#     accountReplicationType: LRS
#     accountTier: Standard
#     allowNestedItemsToBePublic: false
#     isHnsEnabled: true
#     location: UK South
#     publicNetworkAccessEnabled: false
#     resourceGroupName: main_cluster
#   providerConfigRef:
#     name: default