apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deployment-with-sa.fullname" . }}
  labels:
    {{- include "deployment-with-sa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "deployment-with-sa.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "deployment-with-sa.selectorLabels" . | nindent 12 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"